sudo: required
language: java
jdk:
- openjdk11
before_script:
- chmod +x gradlew
script:
- "./gradlew clean check"
- "./gradlew clean runFeatures"
before_install:
- openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
  -in config.json.enc -out config.json -d
